---
title: "diamonds"
author: "ChrisCameron"
date: "10/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
diamonds = read.csv("diamonds.csv", header = T)
head(diamonds)

#always good to do a summary to look for oddities and missing values
summary(diamonds)

#exploratory data analysis 
plot(y = diamonds$Price, x = diamonds$Carats, xlab = "Carats", ylab = "Price")
boxplot(Price~Color, data = diamonds, ylab = "Price", xlab = "Color")
boxplot(Price~Clarity, data = diamonds, ylab = "Price", xlab = "Clarity")
boxplot(Price~Certification, data = diamonds, ylab = "Price", xlab = "Certification")
```
```{r}
#suggest nonconstant variance - try log(price).  quadratic relationship with carats: try carats^2
#these suggest some differences in prices across the categorical variables, but each
#all plots do not account for the effects of other variables (which is why we do multiple regression)

#make log of price
diamonds$Logprice = log(diamonds$Price)

#it helps interpretation to substract the mean from numerical predictors
diamonds$CaratsCent = diamonds$Carats - mean(diamonds$Carats)

#make carats squared
diamonds$Carats2 = diamonds$CaratsCent^2

#let's continue with the EDA. lattice is a great graphics library.
#if you have not installed it, type  install.packages("lattice")
#load it in to R each time you start R
library(lattice)

#you also can make these plots with ggplot -- I will post those commands later.

#let's look for interaction effects using trellis plots.  Let's use LogPrice on Carats by each color
xyplot(Logprice~Carats | Color, data = diamonds)

# slope in each plot is similar, so no strong evidence of interaction between Carats and Color 

#repeat for clarity and certification
xyplot(Logprice~Carats | Clarity, data = diamonds)
xyplot(Logprice~Carats | Certification, data = diamonds)

#same result: similar slopes in each panel, so no strong evidence of interactions with Carats 

#we also can examine trellis plots for box plots to see if there are interactions among categoical vars

bwplot(Logprice~Color | Clarity, data = diamonds)

#for any clarity category, the color box plots have a reasonably similar ordering. 
#So, no strong evidence of interaction between Clarity and Color
#repeat for Color and Certification, and Clarity and Certification (we did not do this in class)

```


```{r}
#### fitting the multiple regression  ####

#so, our candidate model based on EDA is Logprice ~ Carats + Carats^2 + Color + Clarity + Certification + error 

#we need to make dummy variables for all the categorical data

#sample size
n = nrow(diamonds)

#create series of indicator variables for color
diamonds$colorD = rep(0, n)
diamonds$colorD[diamonds$Color == "D"] = 1

diamonds$colorE = rep(0, n)
diamonds$colorE[diamonds$Color == "E"] = 1

diamonds$colorF = rep(0, n)
diamonds$colorF[diamonds$Color == "F"] = 1

diamonds$colorG = rep(0, n)
diamonds$colorG[diamonds$Color == "G"] = 1

diamonds$colorH = rep(0, n)
diamonds$colorH[diamonds$Color == "H"] = 1

diamonds$colorI = rep(0, n)
diamonds$colorI[diamonds$Color == "I"] = 1

#create series of indicator variables for clarity
diamonds$clarityIF = rep(0, n)
diamonds$clarityIF[diamonds$Clarity == "IF"] = 1

diamonds$clarityVS1 = rep(0, n)
diamonds$clarityVS1[diamonds$Clarity == "VS1"] = 1

diamonds$clarityVS2 = rep(0, n)
diamonds$clarityVS2[diamonds$Clarity == "VS2"] = 1

diamonds$clarityVVS1 = rep(0, n)
diamonds$clarityVVS1[diamonds$Clarity == "VVS1"] = 1

diamonds$clarityVVS2 = rep(0, n)
diamonds$clarityVVS2[diamonds$Clarity == "VVS2"] = 1

#create series of indicator variables for certification
diamonds$certGIA = rep(0, n)
diamonds$certGIA[diamonds$Certification == "GIA"] = 1

diamonds$certIGI = rep(0, n)
diamonds$certIGI[diamonds$Certification == "IGI"] = 1

diamonds$certHRD = rep(0, n)
diamonds$certHRD[diamonds$Certification == "HRD"] = 1


#Let's fit a multiple linear regression model without transformations, just to see the impact

regPonAll = lm(Price~CaratsCent + colorE + colorF + colorG + colorH + colorI + clarityVS1 + clarityVS2 + clarityVVS1 + clarityVVS2 + certIGI + certHRD, data = diamonds, x=T)

#to view results, see
summary(regPonAll)  

##Let's confirm that the matrix algebra works.  Notice that I added a "x=T" in the lm call. This returns X.

Xmatrix = regPonAll$x
Xmatrix
Yvector = diamonds$Price

##compute X^tX
#use t(X) as the transpose and %*% for matrix multiplication
XtX=t(Xmatrix)%*%Xmatrix
XtX

##take the inverse of XtX
invXtX = solve(XtX)
invXtX
#compute X^tY
XtY = t(Xmatrix)%*%Yvector

#compute MLE
mles = invXtX %*% XtY
mles
```
```{r}
##Let's confirm that the matrix algebra works.  Notice that I added a "x=T" in the lm call. This returns X.

Xmatrix = regPonAll$x
Xmatrix
Yvector = diamonds$Price

##compute X^tX
#use t(X) as the transpose and %*% for matrix multiplication
XtX=t(Xmatrix)%*%Xmatrix
XtX

##take the inverse of XtX
invXtX = solve(XtX)
invXtX
#compute X^tY
XtY = t(Xmatrix)%*%Yvector

#compute MLE
mles = invXtX %*% XtY
mles

#compute regression variance 
sigma2RSE = t(Yvector - Xmatrix %*% mles) %*% (Yvector - Xmatrix %*% mles) / (n - ncol(Xmatrix))
sqrt(sigma2RSE)

##regression covariance matrix 
Varbetahat = c(sigma2RSE)*invXtX  

colorgminuscolorh = c(0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0, 0, 0)
t(colorgminuscolorh) %*% mles

secolorgminuscolorh = sqrt(t(colorgminuscolorh) %*% Varbetahat %*% (colorgminuscolorh))

secolorgminuscolorh
```

